### Lekéri az alkalmazottakat
GET http://localhost:8080/api/employees

### Elment egy alkalmazottat
POST http://localhost:8080/api/employees
Content-Type: application/json

{
  "name": "Jack Doe",
  "addresses": [
    {
      "city": "Budapest"
    },
    {
      "city": "Baja"
    }
  ]
}

### Alkalmazott lekérése azonosító alapján
GET http://localhost:8080/api/employees/28

### Alkalmazott lekérése azonosító alapján - not found
GET http://localhost:8080/api/employees/666

### Alkalmazott módosítása
PUT http://localhost:8080/api/employees/28
Content-Type: application/json

{
  "id": 28,
  "name": "John DoeXXX"
}

### Törli az alkalmazottat
DELETE http://localhost:8080/api/employees/28